name: bmi_end
description: "Bmi Calculator"

publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.2
  syncfusion_flutter_gauges: ^25.1.35
  syncfusion_flutter_sliders: ^25.1.35

  # Save Data
  shared_preferences: ^2.2.0

 # finish App
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/font_icon.jpg"
  min_sdk_android: 21

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - images/electrocardiogram.png
    - images/font_icon.jpg

  fonts:
    - family: LibreBaskerville
      fonts:
        - asset: fonts/LibreBaskerville-Bold.ttf
